version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './docker/services/nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf'
      - './app/public:/var/www/site.local/public'
      - './docker/data/nginx/logs:/var/log/nginx'
    links:
      - php
    restart: always

  php:
    build: ./docker/images/php/7.2
    links:
      - mysql
    volumes:
      - './app:/var/www/site.local'
      - './docker/data/php/conf.d:/usr/local/etc/php/conf.d'
      - './docker/services/php/conf.d/php.ini:/usr/local/etc/php/conf.d/40-custom.ini'
    restart: always

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - './docker/data/mysql:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'qwe123'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
